name: Sonucu Portfolio Reposuna Gönder

on:
  push:
    paths:
      # SADECE üretilen sonuç dosyası değişince çalış
      - 'portfolio_review.json'
    branches:
      - main

jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Kaynak (Marketwatch) Çek
        uses: actions/checkout@v3

      - name: Hedef (PortfolioReview) Çek
        uses: actions/checkout@v3
        with:
          repository: 'navimod-web/portfolioreview' # Kendi kullanıcı adınızı yazın
          token: ${{ secrets.ACTION_TOKEN }}
          path: 'hedef-repo'
          ref: 'master' # Hedef reponun branch adı (main veya master)

      - name: Dosyayı Kopyala
        run: |
          # Sadece sonuç dosyasını hedefin ana dizinine atıyoruz
          cp portfolio_review.json hedef-repo/

      - name: Karşıya Yükle
        run: |
          cd hedef-repo
          git config user.name "Transfer Botu"
          git config user.email "bot@transfer.com"
          
          git add portfolio_review.json
          git commit -m "Yeni portfolio verisi geldi" || echo "Degisiklik yok"
          git push
